# Generated by Django 5.0.2 on 2024-03-03 19:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener exactamente 10 dígitos.', regex='^\\d{10}$')])),
                ('description', models.TextField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('text', models.TextField(max_length=5000, validators=[django.core.validators.MinLengthValidator(5)])),
                ('comment', models.TextField(max_length=700, null=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('date_time_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.autor')),
            ],
        ),
    ]
