# Generated by Django 5.0.2 on 2024-03-19 21:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsreceived',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='paymentsreceived',
            name='hour',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
