# Generated by Django 5.0.2 on 2024-03-03 22:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('date_time_create', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('date_time_create', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('key', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='La key del maestro debe tener exactamente 8 dígitos.', regex='^\\d{8}$')])),
                ('date_time_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('subjects', models.ManyToManyField(related_name='teachers', to='school.subject')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='school.teachercategory')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener exactamente 10 dígitos.', regex='^\\d{10}$')])),
                ('direction', models.TextField(max_length=1000, null=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='school.teacher')),
            ],
        ),
    ]
