# Generated by Django 5.0.2 on 2024-03-03 06:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('text', models.TextField(max_length=5000, validators=[django.core.validators.MinLengthValidator(5)])),
                ('score', models.PositiveIntegerField(default=5, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
