# Generated by Django 5.0.2 on 2024-03-03 06:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationTwo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='text',
            field=models.TextField(max_length=3000, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
