# Generated by Django 5.0.2 on 2024-03-03 06:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationTwo', '0002_alter_notes_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='date_time_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
